@csrf
<div class="grid gap-5 sm:grid-cols-2">
    <label class="text-sm font-medium text-slate-700">NIM<input name="nim" value="{{ old('nim', $mahasiswa->nim ?? '') }}" required class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5"></label>
    <label class="text-sm font-medium text-slate-700">Nama Mahasiswa<input name="nama_mahasiswa" value="{{ old('nama_mahasiswa', $mahasiswa->nama_mahasiswa ?? '') }}" required class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5"></label>
    <label class="text-sm font-medium text-slate-700">Jenis Kelamin<select name="jenis_kelamin" required class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5"><option value="L" @selected(old('jenis_kelamin', $mahasiswa->jenis_kelamin ?? '') === 'L')>Laki-laki</option><option value="P" @selected(old('jenis_kelamin', $mahasiswa->jenis_kelamin ?? '') === 'P')>Perempuan</option></select></label>
    <label class="text-sm font-medium text-slate-700">Program Studi<select name="prodi_id" required class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5"><option value="">Pilih prodi</option>@foreach ($prodis as $prodi)<option value="{{ $prodi->id }}" @selected((string) old('prodi_id', $mahasiswa->prodi_id ?? '') === (string) $prodi->id)>{{ $prodi->nama_prodi }}</option>@endforeach</select></label>
</div>
<label class="mt-5 block text-sm font-medium text-slate-700">Alamat<textarea name="alamat" required rows="3" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5">{{ old('alamat', $mahasiswa->alamat ?? '') }}</textarea></label>
<label class="mt-5 block text-sm font-medium text-slate-700">Path Foto Mahasiswa <span class="font-normal text-slate-400">(opsional)</span><input name="foto_mahasiswa" value="{{ old('foto_mahasiswa', $mahasiswa->foto_mahasiswa ?? '') }}" class="mt-2 w-full rounded-lg border border-slate-300 px-3 py-2.5"></label>
<div class="mt-6 flex justify-end gap-3"><a href="{{ route('mahasiswa.index') }}" class="rounded-lg px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-100">Batal</a><button class="rounded-lg bg-campus px-4 py-2.5 text-sm font-semibold text-white hover:bg-navy">Simpan</button></div>